---
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'lib/recipe.rb'
    - 'lib/automate_liveness_agent/vendor/**/**'
    - 'lib/macos/**'
    - 'spec/examples.txt'
    - 'build/*'
    - 'test/cookbooks/**/*'
