language: ruby
rvm:
  - 2.3.3
  - 2.4.1
  - 2.5.0

env:
  -
  - TEST_BUILD_ARTIFACT=1
  - CHEFSTYLE=true
  - COOKSTYLE=true

branches:
  only:
    - master

matrix:
  exclude:
    # Only execute the linting checks once
    - rvm: 2.5.0
      env: CHEFSTYLE=true
    - rvm: 2.5.0
      env: COOKSTYLE=true
