language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.6.3

env:
  - TEST_BUILD_ARTIFACT=1
  - CHEFSTYLE=true
  - COOKSTYLE=true

branches:
  only:
    - master

matrix:
  exclude:
    # Only execute the linting checks once and always execute on the latest
    # ruby so we pull in the latest linters.
    - rvm: 2.3.8
      env: CHEFSTYLE=true
    - rvm: 2.3.8
      env: COOKSTYLE=true
    - rvm: 2.4.6
      env: CHEFSTYLE=true
    - rvm: 2.4.6
      env: COOKSTYLE=true
